#!/usr/bin/env bash
# This script displays numbers from 1 to 100
# Fizz for multiples of 3, Buzz for multiples of 5, FizzBuzz for both

for i in {1..100}
do
  if [ $((i % 15)) -eq 0 ]; then
    echo "FizzBuzz"
  elif [ $((i % 3)) -eq 0 ]; then
    echo "Fizz"
  elif [ $((i % 5)) -eq 0 ]; then
    echo "Buzz"
  else
    echo "$i"
  fi
done
