#!/usr/bin/env bash
# Counts occurrences of IP and HTTP code without using loops
# Works with small, big, empty, or malformed logs

awk 'NF>=9 {count[$1" "$9]++} 
     END {for (k in count) printf "%6d %s\n", count[k], k}' apache-access.log | sort -rn

