#!/usr/bin/env bash
# Universal awk version for IP and HTTP code counts

awk '
{
    ip = $1
    code = ""
    # Extract the HTTP code after the request in quotes
    for(i=1;i<=NF;i++) {
        if($i ~ /^[0-9]{3}$/) {
            code = $i
            break
        }
    }
    if(ip ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ && code != "") {
        count[ip" "code]++
    }
}
END {
    for (k in count) printf "%6d %s\n", count[k], k
}' apache-access.log | sort -rn

